### ISSUE TITLE
能介绍一下StageLiveDownloader怎么用吗？

### ISSUE THREAD

**Issue by kybom** [anguiao/48Tools#1]
不太懂java,这个工具不会。

**Comment by anguiao** [comment]
昨晚没看到，不好意思。
这个说起来比较麻烦其实，我写得太粗略了，主要是自己用的。
首先需要 FFmpeg ，下载了然后加到环境变量。
然后直接编译运行就可以，有三个参数，URL（类似 http://live.snh48.com/Index/invedio/id/482 这样）、临时文件路径（保存分段的 ts 文件）、下载路径（保存合并生成的 mp4 文件）。
这个主要是为了多线程下载分段的 ts ，直接用 FFmpeg 好像是单线程的（或者是我不会用哈哈）。
你也可以直接用 FFmpeg 来下，打开官方直播，查看网页源代码，找到 m3u8 的地址，直接用 FFmpeg 下载就行，类似 `ffmpeg -i live.m3u8 -acodec copy -bsf:a aac_adtstoasc -vcodec copy output.mp4` 这样（把 live.m3u8 换成真实的地址）。
其实就是个分段的视频列表，你也可以用自己熟悉的语言自己写一个，很简单的。

**Comment by kybom** [comment]
@anguiao 
``ffmpeg -i live.m3u8 -acodec copy -bsf:a aac_adtstoasc -vcodec copy output.mp4``
这个合并的过程中可以加入口袋的lrc字幕吗？

**Comment by anguiao** [comment]
这个是公演直播啊，不是成员直播。
成员直播有一个接口，`https://github.com/xsaiting/pocket48-grab/wiki/HttpRequest-getLiveOne`，返回的 JSON 里面有视频链接和弹幕链接。
合并的话是不会把字幕加进去的，不过lrc是可以转成srt之类的字母的，搜一下应该能搜到。
转换完再把视频和弹幕压制到一起就行。
